
name: Build Release V2

on:
  release:
    types: [created]

jobs:

  build_1_20:
    uses: alexskim/minihud/.github/workflows/releasebuild.yml@pre-rewrite/fabric/1.20.x
    with:
      branch: pre-rewrite/fabric/1.20.x
      java_version: 17
